name: Build and Publish to TestPyPI

on:
  # åªåœ¨æ‰“ tag æ—¶è§¦å‘ï¼ˆæ¯”å¦‚ v1.0.0ï¼‰
  push:
    tags:
      - '*'

jobs:
  build-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # è®¾ç½® pythonç‰ˆæœ¬
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      # å®‰è£…build æ‰“åŒ…å·¥å…·
      - name: Install pypa/build
        run: python -m pip install build --user
      # æ‰“åŒ…ï¼Œæˆä¸ºçœŸæ­£çš„å®‰è£…åŒ…
      - name: Build a binary wheel and source tarball
        run: python -m build --wheel --sdist --outdir dist/
      # è¿›è¡Œä¸Šä¼ 
      - name: Publish distribution ğŸ“¦ to TestPyPI
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/